### ISSUE TITLE
Relion-3.1.3 star file format

### ISSUE THREAD

**Issue by przemekdutka** [builab/subtomo2Chimera#2]
Hi, I was trying to use the script, but I'm getting the following error:

Traceback (most recent call last):
  File "relionsubtomo2ChimeraX.py", line 42, in <module>
    angpix = df_optics.loc[0, 'rlnTomoTiltSeriesPixelSize']	
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1017, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 137, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/Users/przemyslawdutka1/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rlnTomoTiltSeriesPixelSize'

I think it is because my star file format is different and I have different data compared to the tutorial star file, see below. Any suggestions?

# version 30001

data_optics

loop_
_rlnOpticsGroup #1 
_rlnOpticsGroupName #2 
_rlnSphericalAberration #3 
_rlnVoltage #4 
_rlnImagePixelSize #5 
_rlnImageSize #6 
_rlnImageDimensionality #7 
           1 opticsGroup1     2.700000   300.000000     1.687000          168            3

# version 30001

data_particles

loop_
_rlnMicrographName #1 
_rlnCoordinateX #2 
_rlnCoordinateY #3 
_rlnCoordinateZ #4 
_rlnAngleRot #5 
_rlnAngleTilt #6 
_rlnAnglePsi #7 
_rlnCtfMaxResolution #8 
_rlnImageName #9 
_rlnCtfImage #10 
_rlnPixelSize #11 
_rlnOpticsGroup #12 
_rlnGroupNumber #13 
_rlnOriginXAngst #14 
_rlnOriginYAngst #15 
_rlnOriginZAngst #16 
_rlnClassNumber #17 
_rlnNormCorrection #18 
_rlnRandomSubset #19 
_rlnLogLikeliContribution #20 
_rlnMaxValueProbDistribution #21 
_rlnNrOfSignificantSamples #22 
/data/frames/reconstruction/tomoS12.mrc.tomostar  2975.945000   396.369000  2026.642000    -89.73101   112.507723   169.626680     5.800000 ../subtomo/tomoS12.mrc/tomoS12.mrc_0000000_1.69A.mrc ../subtomo/tomoS12.mrc/tomoS12.mrc_0000000_ctf_1.69A.mrc     1.687000            1            1     8.659963     2.789203     1.844483            1     1.000000            1 1.418662e+06     0.346222            6

Thanks!
Przemek

**Comment by builab** [comment]
Hi Przemek,

I think the reason for the difference is that I wrote this specifically for relion 4.0, not relion 3.1. To get the equivalent of rlnTomoTiltSeriesPixelSize, it is rlnImagePixelSize in Relion 3.1 but there might be other differences that will cause new error. Within next month, we are going to try out subtomogram averaging with Relion 3.1 to compare with 4.0, then I can update this script to be compatible with Relion 3.1. 
Huy

**Comment by przemekdutka** [comment]
Hi Huy, 
Thanks for the quick response. I'll try to play around with it. I'll greatly appreciate it if you can share the version for relion 3.1 when you have it. 
Thanks,
Przemek

**Comment by builab** [comment]
Hi Przemek,

I was fixing the script a bit and I realized that making it compatible with Relion 3.1 is quite simple. Since I haven't tested it, you can test it for me then.

You can download the script as it is but comment out the line with Relion 4.0 and uncomment the line with Relion 3.1
Specifically,
Comment out with # line 47 and uncomment line 49
Comment out with # line 53 and uncomment line 55

After that, the script should be compatible with Relion 3.1, at least from the file format that you enter.
However, since your rlnMicrographName is so long, you probably need to make sure that what you enter after --tomoname matches perfectly to rlnMicrographName.
The easy way is to make a copy of your star file & remove the /data/frames/reconstruction/ part from the rlnMicrographName and enter --tomoname tomoS12.mrc.tomostar in the command.
